name: img2webp-gui build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5'

    - name: Set Go OS
      run: set GOOS=windows

    - name: Set Go Arch
      run: set GOARCH=amd64

    - name: Build Executable
      run: go build -a -o img2webp-gui.exe -gcflags=all="-l -B" -ldflags="-s -w -H windowsgui -extldflags '-O2'" .

    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: img2webp-gui
        path: img2webp-gui.exe
